config/routes.rb
Rails.application.routes.draw do
	#session
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	get '/logout', to: 'sessions#logout'

	#user
	get '/signup', to: 'user#new'
	post '/signup', to: 'user#create'

	#task
	get '/completed/:id', to: 'task#completed', as: 'completed'

	#modals
	#task
	get '/modal_for_new_task' , to: 'task#modal_for_new_task'
	get '/modal_for_search', to: 'task#modal_for_search'
	post '/modal_for_search', to: 'task#modal_for_search', default: { format: :js }

	resources :sessions
	resources :user do
		resources :task
	end

	resources :user do
		resources :tasklist
	end

	root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :tasklist

	def self.search(query)
		where('title LIKE ?', "%#{query}%")
	end
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
	belongs_to :user
	has_many :tasks

	def self.search(query)
		where('title LIKE ?', "%#{query}%")
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasklists

	before_save { self.email = email.downcase } 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :email, presence: true, length: { maximum: 255 },
									  format: { with: VALID_EMAIL_REGEX },
									  uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6},
									 allow_nil: true
	has_secure_password

	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper

	def new
	end

	def create
		@user = User.find_by_email(params[:sessions][:email].downcase)
		if @user && @user.authenticate(params[:sessions][:password])
			flash[:success] = "Logged in successfully"
			login(@user)
			showTasklists(@user)
		else
			flash.now[:danger] = "Invalid email or password"
  			render 'new'
  		end
  	end

  	def logout
  		logout
      redirect_to root_path
  	end

  	def showTasklists(user)
  		redirect_to(user_tasklist_index_path(user))
  	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	include ApplicationHelper
	
	def home
	end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
	include TaskHelper
	def new
		@task = Task.new
	end

	#opens up a modal for new task
	#in the same page
	def modal_for_new_task
		respond_to do |format|
			format.js
		end
	end

	#upon completion
	#remove tasks from view
	def completed
		task = Task.find_by_id(params[:id])
		if !task.completed
			task.destroy
		end	
		showTasklists
	end

	#creates a new task bound to corr tasklist
	def create
		tasklist = findTasklist
		task = tasklist.tasks.create(task_params)
		showTasklists
	end

	#redirects to new page to edit task
	def edit
		@task = Task.find_by_id(params[:id])
	end

	#refreshes page upon update 
	#to reflect changes
	def update
		if Task.update(params[:id], task_params)
			showTasklists
		end
	end

	#destroys task by removing from database,
	#user's tasklist
	def destroy
		task_to_remove = Task.find_by_id(params[:id])
		user = User.find_by_id(params[:user_id])
		user_task = user.tasklists.find_by_id(params[:id])
		if !task_to_remove.nil?
			task_to_remove.destroy
			if !user_task.nil?
				user_task.destroy
			end
		end
		showTasklists
	end

	#opens up a modal for viewing search results
	def modal_for_search
		#query is non-empty
		if params[:searchterm]
			@tasks_found = Task.search(params[:searchterm])
			@tasklists_found = Tasklist.search(params[:searchterm])
		#no query given so we display all tasks
		else 
			@tasks_found = Task.all
		end
		respond_to do |format|
			format.js
		end
	end

	#finds and returns the corr tasklist
	def findTasklist
		tasklist_id = params[:tasklist_id]
		tasklist = Tasklist.find_by_id(tasklist_id)
		return tasklist
	end

	#redirects to page to display all tasklists
	def showTasklists
		user = User.find_by_id(params[:user_id])
  		redirect_to(user_tasklist_index_path(user))
  	end

	def task_params
		params.require(:task).permit(:title, :date, :completed, 
									 tasklist_id: params[:tasklist_id])
	end

end

app/controllers/tasklist_controller.rb
class TasklistController < ApplicationController
	def new 
		@tasklist = Tasklist.new
	end

	#creates new tasklist bound to user
	#redirects to page showing all of user's tasklists
	def create
		user = getUser
		tasklist = user.tasklists.create(tasklist_params)
		showTasklists(user)
	end

	#receives user data, corr tasklists
	#renders the show page
	def index
		user = getUser
		@tasklists = user.tasklists
		render 'show'
	end
	
	#shows all tasklists
	def show 
	end

	#removes tasklist from database
	#and from user's tasklists
	def destroy
		tasklist = Tasklist.find_by_id(params[:id])
		user = getUser
		user_tasklist = user.tasklists.find_by_id(params[:id])
		if !tasklist.nil?
			tasklist.destroy
			if !user_tasklist.nil?
				user_tasklist.destroy
			end
		end
		showTasklists(user)
	end

	def showTasklists(user)
  		redirect_to(user_tasklist_index_path(user))
  	end

	def getUser
		return User.find_by_id(params[:user_id])
	end

	def tasklist_params
		params.require(:tasklist).permit(:title, user_id: params[:user_id])
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def new
		@user = User.new
	end

	#signup
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "new user created"
			redirect_to root_path
		else 
			render 'new'
		end
	end

	def show
	end

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include TasklistHelper
	include SessionsHelper
	
	def full_title(title)
		title += ' | Task Manager'
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	@@current_user = nil

	def login(user)
		session[:user_id] = user.id
		@@current_user = user
	end

	def logout
		session[:user_id] = nil
		@@current_user = nil;
	end

	def is_logged_in?(user)
		@@current_user == user
	end

	def is_in_session?
		!@@current_user.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasklist_helper.rb
module TasklistHelper
	def removeCheckedTasks(task_ids)
		task_ids.each do |id| 
			task = Task.find(id)
			if task.checked == true
				task.destroy
			end
		end
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
<small>
    Task Manager
</small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Task Manager", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if params[:user_id].nil? %>
              <li><%= link_to "Home", root_path, class: 'header-btn' %></li>
            <% else %>
              <li><%= link_to "Home", user_tasklist_index_path(params[:user_id]), class: 'header-btn' %></li>
            <% end %>
            
            <% if is_in_session? %>
                <li><%= link_to "Log out", logout_path,  class: 'header-btn' %></li>
            <% else %>
              <li><%= link_to "Log in", login_path, class: 'header-btn' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="/assets/jquery.js" type="text/javascript"></script>
  <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
  <script src="js/bootstrap.js"></script>
  <script src="/js/bootstrap.min.js" type="text/javascript"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/bootstrap.css">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/header' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<div class="center jumbotron">
    <h1><%= full_title(yield(:title)) %></h1>
	</div>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer' %>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
<!DOCTYPE html>
<html>
<body>
  <div class = "wrap">
  <%= button_to "Sign up", signup_path, method: 'get', class: 'button btn-white home-btn' %>
  </div>
</body>
</html>

app/views/task/_edit_task_form.html.erb
<%= form_for @task, url: user_task_path(params[:user_id], @task.id) do |f| %>
	<%= f.label :title, class: "label" %>
	<%= f.text_field :title, class: 'form-control' %>

	<%= f.label :date, class: "label" %>
	<%= f.date_field :date, class: 'form-control' %>
	
	<%= f.submit "Amend", class: "btn btn-primary"%>
<% end %>

app/views/task/_modal_for_new_task.html.erb
<div class="modal" id="modal-center", data-backdrop="">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Task</h5>
      </div>
      <div class="modal-body">
        <%= render 'task_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id=" close-btn" data-dismiss="modal">Close</button>
      </div>
    </div>
</div>
</div>

app/views/task/_modal_for_search.html.erb
<div class="modal" id="search-modal", data-backdrop="">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Relevant Results</h5>
      </div>
      <div class="modal-body">
        <%= render 'task/tasks_found' %>
        <%= render 'tasklist/tasklists_found' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id=" close-btn" data-dismiss="modal">Close</button>
      </div>
    </div>
</div>
</div>

app/views/task/_task_form.html.erb
<%= form_for Task.new, url: user_task_index_path(params[:user_id]), method: 'post' do |f| %>
<%= hidden_field_tag("tasklist_id", params[:tasklist_id]) %>
	<%= f.label :title, class: "label" %>
	<%= f.text_field :title, class: 'form-control' %>

	<%= f.label :date, class: "label" %>
	<%= f.date_field :date, class: 'form-control' %>

<%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/task/_tasks_found.html.erb
<% if @tasks_found.blank? %>
	<p> No tasks found </p>
<% else %>
	<h4>Tasks found: </h4>
	<% @tasks_found.each do |task| %>
	<div class = "row">
		<div class = "col-md-2">
			<h4><%= task.title %></h4>
		</div>
		<div class = "col-md-2">
			<h4><%= task.date %></h4>
		</div>
	</div>
	<% end %> 
<% end %>

app/views/task/edit.html.erb
<% provide(:title, "Add new task") %>
<h1><%= full_title(yield(:title)) %></h1>
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= render 'edit_task_form' %>
	</div>
</div>

app/views/task/modal_for_new_task.js.erb
$(document).ready(function() {

	$("#modal_form").html("<%= escape_javascript(render :partial => 'modal_for_new_task') %>");
	$("#modal-center").modal("show");

	  $("#close-btn").click(function() {
	    $('#modal-center').modal('hide');
	});
});

app/views/task/modal_for_search.js.erb
$(document).ready(function() {
	$("#search_results_modal").html("<%= escape_javascript(render :partial => 'modal_for_search') %>");
	$("#search-modal").modal("show");
	  $("#close-btn").click(function() {
	    $('#search-modal').modal('hide');
	});
});

app/views/task/new.html.erb
<% provide(:title, "New task") %>
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= render 'task_form' %>
	</div>
</div>

app/views/tasklist/_modal_for_search.html.erb
<div class="modal" id="search-modal", data-backdrop="">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Task</h5>
      </div>
      <div class="modal-body">
        <%= render '/task/tasks_found' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id=" close-btn" data-dismiss="modal">Close</button>
      </div>
    </div>
</div>
</div>

app/views/tasklist/_new_tasklist_form.html.erb
<%= form_for @tasklist, url: user_tasklist_index_path(params[:user_id]) do |f| %>
	<%= f.label :title, class: "label" %>
	<%= f.text_field :title, class: 'form-control' %>
<%= f.submit "Add", class: "button  show-btn" %>
<% end %>

app/views/tasklist/_searchfield.html.erb
  <%= form_tag( { action: 'modal_for_search', controller: 'task' }, { remote: true } ) do %>
  <%= text_field_tag 'searchterm', params[:searchterm], class: "input-large search-query" %>
  <%= button_to  'Search!', modal_for_search_path, remote: true, 'data-toggle' => 'modal', 'data-target' =>'#search-modal', 'data-backdrop' => '', class: "button" %>
  <% end %>

app/views/tasklist/_tasklists.html.erb
<div class = "row">
    <% @tasklists.each do |tasklist| %>
    <% @tasklist_id = tasklist.id %>
      <div class = "card card-cascade wider">
        <div class="view overlay hm-white-slight">
        </div>
        <div class = "card-body">
        <h2 class = "card-title text-center"><%= tasklist.title %></h2>
        <table>
          <% tasklist.tasks.each do |task| %>
          <tr class = "row">
          <td class="col-md-3">
          <h4 class = "card-text">
            <%= task.title %>
          </h4>
          </td>
          <td class="col-md-3">
          <h5 class = "card-text">
           <%= task.date %>
          </h5>
          </td>
          <td class="col-sm-5">
            <%= button_to "Done", completed_path(task.id), params: { tasklist_id: @tasklist_id, user_id: @user_id }, method: 'get', class: 'button tasklist-btn' %>
          </td>
          <td class="col-sm-5">
            <%= link_to "Delete", user_task_path(@user_id, task.id, tasklist_id: @tasklist_id), method: 'delete', :class => 'button tasklist-btn' %>
          </td>
          <td class="col-sm-3">
          <%= link_to "Edit", edit_user_task_path(@user_id, task.id, tasklist_id: @tasklist_id), method: 'get', :class => 'button tasklist-btn' %>
          </td>
        </tr>
        <% end %>
        </table>
        <div class = "row">
         <%= link_to "Delete", user_tasklist_path(@user_id, @tasklist_id), method: 'delete', :class => 'button tasklist-btn'%>
         <%= button_to "Add Task", modal_for_new_task_path(user_id: @user_id, tasklist_id: tasklist.id), method: 'get', remote: true, 'data-toggle' => 'modal', 'data-target' =>'#modal-center', 'data-backdrop' => '', class: 'button tasklist_btn add-task-btn btn-white' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasklist/_tasklists_found.html.erb
<% if @tasklists_found.blank? %>
	<p> No Task Lists found </p>
<% else %>
	<h4>Task Lists found: </h4>
	<% @tasklists_found.each do |tasklist| %>
	<ul>
		<li><h4><%= tasklist.title %></h4></li>
		<% tasklist.tasks.each do |task| %>
		<div class = "row">
			<div class = "col-sm-6">
				<p><%= task.title %></p>
			</div>
			<div class = "col-sm-6">
				<p><%= task.date %></p>
			</div>
		</div>
		<% end %>
	</ul>
	<% end %> 
<% end %>

app/views/tasklist/modal_for_search.js.erb
$(document).ready(function() {

	$("#search_results_modal").html("<%= escape_javascript(render :partial => 'modal_for_search') %>");
	$("#search-modal").modal("show");

	  $("#close-btn").click(function() {
	    $('#search-modal').modal('hide');
	});
});

app/views/tasklist/new.html.erb
<% provide(:title, "New Task") %>
<div class = "row">
	<div class = "wrap">
		<%= render 'new_tasklist_form' %>
	</div>
</div>

app/views/tasklist/show.html.erb
<% provide(:title, "All tasks")%>
<% @user_id = params[:user_id] %>
<body>
  <div class ="row">
  <%= link_to "Create New Tasklist", new_user_tasklist_path(@user_id), method: 'get', class: 'button btn-white main-btn' %>
   <%= render 'searchfield' %>
  </div>
 
  <%= render 'tasklists' %>
    <div id = "modal_form"></div>
    <div id = "search_results_modal"><%= render '/task/modal_for_search' %></div>
</body>

app/views/user/_error_msg.html.erb
<% if @user.errors.any? %>
	<div id = "error_expl">
		<div class = "alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/user/_new_user.html_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>
<%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>

app/views/user/_new_user_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>
<%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>

app/views/user/new.html.erb
<% provide(:title, "Sign up") %>
<%= render 'error_msg' %>
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= render 'new_user_form' %>
	</div>
</div>